version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-vpub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yourpassword}
      POSTGRES_DB: ${POSTGRES_DB:-vpub}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  vpub:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      SESSION_KEY: ${SESSION_KEY}
      CSRF_KEY: ${CSRF_KEY}
      CSRF_SECURE: ${CSRF_SECURE}
      PORT: ${PORT}
      POSTGRES_MAX_OPEN_CONNECTIONS: ${POSTGRES_MAX_OPEN_CONNECTIONS}
      POSTGRES_MAX_IDLE_CONNECTIONS: ${POSTGRES_MAX_IDLE_CONNECTIONS}
      POSTGRES_MAX_LIFETIME: ${POSTGRES_MAX_LIFETIME}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${HOST_PORT}:${PORT}"
    restart: unless-stopped
    develop:
      watch:
        - path: ./
          action: rebuild

volumes:
  db_data:
