// Code generated by go generate; DO NOT EDIT.

package handler

var TplMap = map[string]string{
	"account": `{{ define "title" }}Account{{ end }}

{{ define "content" }}
    <h1>Account</h1>

    <form action="/update-account" method="post">
        {{ .csrfField }}
        {{ if .form.Picture }}
            <img alt="{{ .form.PictureAlt }}" src="{{ .form.Picture }}" width="80" height="80" style="object-fit: contain;"/>
        {{ else }}
            <svg width="80" height="80" xmlns="http://www.w3.org/2000/svg">
                <rect width="80" height="80" fill="rgba(0,0,0,40%)"/>
                <text x="40" y="40" font-size="30" font-family="Sans-Serif" font-weight="bold" fill="#ffffff"
                      text-anchor="middle" alignment-baseline="middle">{{ printf "%c" (index .logged.Name 0) }}
                </text>
            </svg>
        {{ end }}
        <div class="field">
            <label for="picture">Picture URL</label>
            <input type="url" name="picture" id="picture" value="{{ .form.Picture }}">
        </div>
        <div class="field">
            <label for="picture-alt">Picture alt text</label>
            <input type="text" name="picture-alt" id="picture-alt" value="{{ .form.PictureAlt }}">
        </div>
        <div class="field">
            <label for="about">About</label>
            <textarea name="about" id="about" autofocus>{{ .form.About }}</textarea>
        </div>
        <input type="submit" value="Submit">
    </form>
    </section>
{{ end }}
`,
	"admin": `{{ define "breadcrumb" }} > Admin{{ end }}
{{ define "content"}}
    <h1>Admin</h1>
    <nav>
        <ul>
            <li><a href="/admin/settings/edit">Edit settings</a></li>
            <li><a href="/admin/keys">Manage keys</a></li>
            <li><a href="/admin/boards">Manage boards</a></li>
            <li><a href="/admin/forums">Manage forums</a></li>
            <li><a href="/admin/users">Manage users</a></li>
        </ul>
    </nav>
{{ end }}`,
	"admin_board": `{{ define "content"}}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        Boards
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Boards</h1>
    <p>
        {{ if .hasForums }}
            <a href="/admin/boards/new">New board</a>
        {{ else }}
            <a href="/admin/forums">Create a forum</a> to create boards
        {{ end }}
    </p>
    <table>
        <thead>
        <tr>
            <th class="grow">Board</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {{ if .forums }}
            {{ range .forums }}
                <tr class="forum">
                    <td colspan="4">{{ .Name }}</td>
                </tr>
                {{ range .Boards }}
                    <tr>
                        <td>
                            <a href="/boards/{{ .Id }}">{{ .Name }}</a><br>{{ .Description }}
                        </td>
                        <td class="center"><a href="/admin/boards/{{ .Id }}/edit">Edit</a></td>
                        <td class="center"><a href="/admin/boards/{{ .Id }}/remove">Delete</a></td>
                    </tr>
                {{ end }}
            {{ end }}
        {{ else }}
            <tr>
                <td colspan="2">No boards yet.</td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}`,
	"admin_board_create": `{{ define "title" }}New board{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        <a href="/admin/boards">Boards</a>
                        <ul>
                            <li>Create board</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Create board</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/admin/boards/save" method="post">
        {{ .csrfField }}
        {{ template "board_form" .form }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"admin_board_edit": `{{ define "title" }}Edit board{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="{{ .root }}/admin">Admin</a>
                <ul>
                    <li>
                        <a href="/admin/boards">Boards</a>
                        <ul>
                            <li>Edit board</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Edit board</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/admin/boards/{{ .board.Id }}/update" method="post">
        {{ .csrfField }}
        {{ template "board_form" .form }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"admin_board_remove": `{{ define "content" }}

    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    Are you sure you want to delete the following board?
    <p>{{ .board.Name }}</p>
    <form action="/admin/boards/{{ .board.Id }}/remove" method="post">
        {{ .csrfField }}
        <input type="submit" value="Submit">
    </form>
{{ end }}`,
	"admin_forum": `{{ define "content"}}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        Forums
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Forums</h1>
    <p><a href="/admin/forums/new">New forum</a></p>
    <table>
        <thead>
        <tr>
            <th class="grow">Forum</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {{ if .forums }}
            {{ range .forums }}
                <tr>
                    <td>
                        {{ .Name }}
                    </td>
                    <td class="center"><a href="/admin/forums/{{ .Id }}/edit">Edit</a></td>
                    <td class="center"><a href="/admin/forums/{{ .Id }}/remove">Delete</a></td>
                </tr>
            {{ end }}
        {{ else }}
            <tr>
                <td colspan="2">No forums yet.</td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}`,
	"admin_forum_create": `{{ define "title" }}New forum{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        <a href="/admin/forums">Forums</a>
                        <ul>
                            <li>Create forum</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Create forum</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/admin/forums/save" method="post">
        {{ .csrfField }}
        {{ template "forum_form" .form }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"admin_forum_edit": `{{ define "title" }}Edit forum{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        <a href="/admin/forums">Forums</a>
                        <ul>
                            <li>Edit forum</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Edit forum</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/admin/forums/{{ .forum.Id }}/update" method="post">
        {{ .csrfField }}
        {{ template "forum_form" .form }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"admin_forum_remove": `{{ define "content" }}

    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    Are you sure you want to delete the following forum?
    <p>{{ .forum.Name }}</p>
    <form action="/admin/forums/{{ .forum.Id }}/remove" method="post">
        {{ .csrfField }}
        <input type="submit" value="Submit">
    </form>
{{ end }}`,
	"admin_keys": `{{ define "title" }}Keys{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        Keys
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Keys</h1>
    <form action="/admin/keys/save" method="post" class="action">
        {{ .csrfField }}
        <input type="submit" value="Create key">
    </form>

    <table>
        <thead>
        <tr>
            <th class="grow">Key</th>
            <th>Created</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {{ range .keys }}
            <tr>
                <td>{{ .Key }}</td>
                <td class="center">{{ iso8601 .CreatedAt }}</td>
                <td class="center"><a href="/admin/keys/{{ .Id }}/remove">Delete</a></td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}
`,
	"admin_settings_edit": `{{ define "breadcrumb" }} > <a href="/admin">Admin</a> > Settings{{ end }}
{{ define "content"}}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        Edit Settings
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Edit Settings</h1>
    <form action="/admin/settings/update" method="post">
        {{ .csrfField }}
        <div class="field">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ .form.Name }}" autocomplete="off" maxlength="120"
                   autofocus/>
        </div>
        <div class="field">
            <label for="url">URL</label>
            <input type="url" name="url" id="url" value="{{ .form.URL }}" autocomplete="off"/>
        </div>
        <div class="field">
            <label for="lang">Site language</label>
            <input type="text" name="lang" id="lang" value="{{ .form.Lang }}" autocomplete="off" maxlength="2"/>
        </div>
        <div class="field">
            <label for="footer">Footer</label>
            <textarea class="editor" name="footer" id="footer">{{ .form.Footer }}</textarea>
        </div>
        <div class="field">
            <label for="css">CSS</label>
            <textarea class="editor" name="css" id="css">{{ .form.Css }}</textarea>
        </div>
        <div class="field">
            <label for="per-page">Per page</label>
            <input type="number" name="per-page" id="per-page" value="{{ .form.PerPage }}" autocomplete="off" required/>
        </div>
        <input type="submit" value="Submit">
    </form>
    </table>
{{ end }}`,
	"admin_user": `{{ define "content"}}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>Users</li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Users</h1>
    <table>
        <thead>
        <tr>
            <th class="grow">User</th>
            <th>Edit</th>
            <th>Password</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {{ range .users }}
            <tr>
                <td>{{ .Name }}</td>
                <td class="center"><a href="/admin/users/{{ .Id }}/edit">Edit</a></td>
                <td class="center"><a href="/reset-password?hash={{ .Hash }}">Reset</a></td>
                <td class="center"><a href="/admin/users/{{ .Id }}/remove">Delete</a></td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}`,
	"admin_user_edit": `{{ define "title" }}Edit user{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/admin">Admin</a>
                <ul>
                    <li>
                        <a href="/admin/users">Users</a>
                        <ul>
                            <li>Edit users</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <h1>Edit user</h1>
    <form action="/admin/users/{{ .user.Id }}/update" method="post">
        {{ .csrfField }}
        <div class="field">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ .form.Username }}" autocomplete="off" maxlength="120"
                   required autofocus/>
        </div>
        <div class="field">
            <label for="picture">Picture</label>
            <input type="text" name="picture" id="picture" value="{{ .form.Picture }}" autocomplete="off"/>
        </div>
        <div class="field">
            <label for="about">About</label>
            <textarea class="editor" name="about" id="about">{{ .form.About }}</textarea>
        </div>
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"admin_user_remove": `{{ define "content" }}

    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    Are you sure you want to delete the following user?
    <p>{{ .user.Name }}</p>
    <form action="/admin/users/{{ .user.Id }}/remove" method="post">
        {{ .csrfField }}
        <input type="submit" value="Submit">
    </form>
{{ end }}`,
	"board": `{{ define "head" }}
    <link type="application/atom+xml" rel="alternate"
          href="{{ .settings.URL}}boards/{{ .board.Id }}/feed.atom"/>
{{ end }}
{{ define "content" }}
    {{ template "forum_nav" .navigation }}
    <h1>{{ .board.Name }}</h1>
    {{ if logged }}
        {{ if .board.Forum.IsLocked }}
            <p>This forum is locked.</p>
        {{ end }}
        {{ if .board.IsLocked }}
            <p>This board is locked.</p>
        {{ end }}
        {{ if or (and (not .board.IsLocked) (not .board.Forum.IsLocked)) .logged.IsAdmin }}
            <form action="/boards/{{ .board.Id }}/new-topic" method="get" class="action">
                {{ .csrfField }}
                <input type="submit" value="New topic">
            </form>
        {{ end }}
    {{ end }}

    <section>
        <table>
            <thead>
            <tr>
                <th class="grow">Subject</th>
                <th>Author</th>
                <th>Replies</th>
                <th>Updated</th>
            </tr>
            </thead>
            <tbody>
            {{ if .topics }}
                {{ range .topics }}
                    <tr>
                        <td>
                            {{ if .IsSticky }}<span class="sticky">[Sticky]</span>{{ end }}
                            <a href="/topics/{{ .Id }}">{{ .Post.Subject }}</a>
                        </td>
                        <td class="center"><a href="/users/{{ .Post.User.Id }}">{{ .Post.User.Name }}</a></td>
                        <td class="center">{{ dec .Posts }}</td>
                        <td><a href="/topics/{{ .Id }}/newest">{{ iso8601 .UpdatedAt }}</a></td>
                    </tr>
                {{ end }}
            {{ else }}
                <tr>
                    <td colspan="4">No topics yet.</td>
                </tr>
            {{ end }}
            </tbody>
        </table>
        {{ template "pagination" .pagination }}
    </section>
{{ end }}
`,
	"boards": `{{ define "content"}}
    {{ template "forum_nav" .navigation }}
    <h1>{{ .forum.Name }}</h1>
    {{ if .forum.IsLocked }}
        <p>This forum is locked.</p>
    {{ end }}
    <table>
        <thead>
        <tr>
            <th class="grow">Board</th>
            <th>Topics</th>
            <th>Posts</th>
            <th>Updated</th>
        </tr>
        </thead>
        <tbody>
        {{ if .boards }}
            {{ range .boards }}
                <tr>
                    <td>
                        <a href="/boards/{{ .Id }}">{{ .Name }}</a><br>{{ .Description }}
                    </td>
                    <td class="center">{{ .Topics }}</td>
                    <td class="center">{{ .Posts }}</td>
                    <td class="center"><a href="/boards/{{ .Id }}/newest">{{ iso8601 .UpdatedAt }}</a></td>
                </tr>
            {{ end }}
        {{ else }}
            <tr>
                <td colspan="4">No boards yet.</td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}`,
	"confirm_remove_post": `{{ define "content" }}
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    Are you sure you want to delete the following post?
    <p>{{ syntax .post.Content }}</p>
    <form action="/posts/{{ .post.Id }}/remove" method="post">
        {{ .csrfField }}
        <input type="submit" value="Submit">
    </form>
{{ end }}`,
	"create_post": `{{ define "title" }}Create Post{{ end }}
{{ define "content" }}
    <nav class="breadcrumb">
        <ul>
            <li>
                <a href="/">All forums</a>
                <ul>
                    <li>
                        <a href="/forums/{{ .board.Forum.Id }}">{{ .board.Forum.Name }}</a>
                        <ul>
                            <li>
                                <a href="/boards/{{ .board.Id }}">{{ .board.Name }}</a>
                                <ul>
                                    <li>{{ .topic.Post.Subject }}</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <h1>Create Post</h1>

    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    <form action="/posts/save" method="post">
        {{ .csrfField }}
        {{ template "post_form" .form }}
        <input type="submit" value="Reply">
    </form>
{{ end }}
`,
	"create_topic": `{{ define "title" }}New topic{{ end }}
{{ define "content" }}
    {{ template "forum_nav" .navigation }}
    <h1>New topic</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/boards/{{ .board.Id }}/save-topic" method="post">
        {{ .csrfField }}
        <input type="hidden" name="boardId" value="{{ .form.BoardId }}">
        {{ template "post_form" .form.PostForm }}
        {{ if .logged.IsAdmin }}
            {{ template "topic_form" .form }}
        {{ end }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"edit_post": `{{ define "title" }}Edit Post{{ end }}
{{ define "content" }}
    {{ template "forum_nav" .navigation }}

    <h1>Edit Post</h1>

    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}

    <form action="/posts/{{ .post.Id }}/update" method="post">
        {{ .csrfField }}
        {{ template "post_form" .form }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"edit_topic": `{{ define "title" }}Edit topic{{ end }}
{{ define "content" }}
    <h1>Edit topic</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/topics/{{ .form.Id }}/update" method="post">
        {{ .csrfField }}
        <input type="hidden" name="boardId" value="{{ .form.BoardId }}">
        {{ template "post_form" .form.PostForm }}
        {{ if .logged.IsAdmin }}
            {{ template "topic_form" .form }}
        {{ end }}
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"index": `{{ define "content"}}
    {{ if .settings.Name }}
        <h1>{{ .settings.Name }}</h1>
    {{ else }}
        <h1>Forums</h1>
    {{ end }}
    <table>
        <thead>
        <tr>
            <th class="grow">Forum</th>
            <th>Topics</th>
            <th>Posts</th>
            <th>Updated</th>
        </tr>
        </thead>
        <tbody>
        {{ if .forums }}
            {{ range .forums }}
                <tr class="forum">
                    <td colspan="4"><a href="/forums/{{ .Id }}">{{ .Name }}</a></td>
                </tr>
                {{ range .Boards }}
                    <tr>
                        <td>
                            <a href="/boards/{{ .Id }}">{{ .Name }}</a><br>{{ .Description }}
                        </td>
                        <td class="center">{{ .Topics }}</td>
                        <td class="center">{{ .Posts }}</td>
                        <td class="center">
                            {{ if .Topics }}
                                <a href="/boards/{{ .Id }}/newest">{{ iso8601 .UpdatedAt }}</a>
                            {{ else }}
                                {{ iso8601 .UpdatedAt }}
                            {{ end }}
                        </td>
                    </tr>
                {{ end }}
            {{ end }}
        {{ else }}
            <tr>
                <td colspan="4">No forums yet.</td>
            </tr>
        {{ end }}
        </tbody>
    </table>
{{ end }}`,
	"login": `{{ define "title" }}Login{{ end }}

{{ define "content" }}
    <h1>Login</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/login" method="post" class="auth-form">
        {{ .csrfField }}
        <div class="field">
            <label for="name">Username</label>
            <input type="text" name="name" id="name" autocomplete="off" required/>
        </div>
        <div class="field">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required/>
        </div>
        <input type="submit" value="Login">
    </form>
{{ end }}`,
	"posts": `{{ define "content" }}
    <h1>Posts</h1>

    <section>
        <table>
            <thead>
            <tr>
                <th class="grow">Subject</th>
                <th>Author</th>
                <th>Posted</th>
            </tr>
            </thead>
            <tbody>
            {{ if .posts }}
                {{ range .posts }}
                    <tr>
                        <td><a href="/topics/{{ .TopicId }}#{{ .Id }}">{{ .Subject }}</a></td>
                        <td class="center"><a href="/users/{{ .User.Id }}">{{ .User.Name }}</a></td>
                        <td class="center">{{ iso8601 .CreatedAt }}</td>
                    </tr>
                {{ end }}
            {{ else }}
                <tr>
                    <td colspan="4">No posts yet.</td>
                </tr>
            {{ end }}
            </tbody>
        </table>
        {{ template "pagination" .pagination }}
    </section>
{{ end }}`,
	"register": `{{ define "title" }}Register{{ end }}

{{ define "content" }}
    <h1>Register</h1>
    {{ if .errorMessage }}
        <p class="errors">{{ .errorMessage }}</p>
    {{ end }}
    <form action="/register" method="post" class="auth-form">
        {{ .csrfField }}
        <div class="field">
            <label for="name">Username</label>
            <input type="text" id="name" name="name" autocomplete="off" value="{{ .form.Username }}" maxlength="15"
                   required/>
        </div>
        <div class="field">
            <label for="password">Password</label>
            <input type="password" id="password" name="password" required/>
        </div>
        <div class="field">
            <label for="confirm">Confirm password</label>
            <input type="password" id="confirm" name="confirm" required/>
        </div>
        <div class="field">
            <label for="key">Key</label>
            <input type="text" id="key" name="key" required/>
        </div>
        <input type="submit" value="Submit">
    </form>
{{ end }}
`,
	"reset_password": `{{ define "title" }}Reset password{{ end }}

{{ define "content" }}
    <h1>Reset password</h1>
    {{ if .error }}
        <p class="error">{{ .error }}</p>
    {{ end }}
    <form action="/reset-password" method="post" class="auth-form">
        {{ .csrfField }}
        <input name="hash" type="hidden" value="{{ .hash }}">
        <div class="field">
            <label for="password">New password</label>
            <input type="password" id="password" name="password"/>
        </div>
        <div class="field">
            <label for="confirm">Confirm password</label>
            <input type="password" id="confirm" name="confirm" required/>
        </div>
        <input type="submit" value="Submit">
    </form>
{{ end }}`,
	"topic": `{{ define "head" }}
    <link type="application/atom+xml" rel="alternate" href="{{ .settings.URL}}topics/{{ .topic.Id }}/feed.atom"/>
    <meta property="article:published_time" content="{{ iso8601Time (index .posts 0).CreatedAt }}">
    {{ if ne (index .posts 0).CreatedAt (index .posts 0).UpdatedAt }}
        <meta property="article:modified_time" content="{{ iso8601Time (index .posts 0).UpdatedAt }}">
    {{ end }}
    <meta property="article:author" content="{{ .settings.URL}}users/{{ (index .posts 0).User.Id }}">
    <meta property="author" content="{{ (index .posts 0).User.Name }}">
    <meta property="og:description" content="{{ printf "%.100s" (index .posts 0).Content }}">
    <meta property="og:title" content="{{ (index .posts 0).Subject }}">
    <meta property="og:site_name" content="{{ .settings.Name }}">
    <meta property="og:locale" content="{{ .settings.Lang }}">
    <meta property="article:section" content="{{ .board.Name }}">

    <meta property="raw" content="{{ printf "%+v" . }}">
{{ end }}
{{ define "content"}}
    {{ template "forum_nav" .navigation }}
    <h1>{{ .topic.Post.Subject }}</h1>
    <table class="topic">
        <thead>
        <tr>
            <th>Author</th>
            <th>Topic</th>
        </tr>
        </thead>
        <tbody>
        {{ range .posts }}
            <tr id="{{ .Id }}">
                <td class="col-author">
                    <a href="/users/{{ .User.Id }}">{{ .User.Name }}</a>
                    <p>
                        {{ if .User.Picture }}
                            <img alt="{{ .User.PictureAlt }}" src="{{ .User.Picture }}" width="80" height="80" style="object-fit: contain;"/>
                        {{ else }}
                            <svg width="80" height="80" xmlns="http://www.w3.org/2000/svg">
                                <rect width="80" height="80" fill="rgba(0, 0, 0, 40%)"/>
                                <text x="40" y="40" font-size="30" font-family="Sans-Serif" font-weight="bold" fill="#ffffff"
                                      text-anchor="middle" alignment-baseline="middle">{{ printf "%c" (index .User.Name 0) }}
                                </text>
                            </svg>
                        {{ end }}
                    </p>
                </td>
                <td>
                    <div class="posted">
                        <span>Posted on <time datetime="{{ iso8601Time .CreatedAt }}"
                                              title="{{ timeAgo .CreatedAt }}">{{ iso8601Time .CreatedAt }}</time></span>
                        {{ if and (eq $.topic.Post.Id .Id) $.logged.IsAdmin }}
                            <a href="/topics/{{ $.topic.Id }}/edit">edit</a> <a
                                    href="/posts/{{ .Id }}/remove">remove</a>
                        {{ else }}
                            {{ if or (hasPermission .User.Name) $.logged.IsAdmin }}
                                <a href="/posts/{{ .Id }}/edit">edit</a> <a href="/posts/{{ .Id }}/remove">remove</a>
                            {{ end }}
                        {{ end }}
                        <hr/>
                    </div>
                    <div>{{ syntax .Content }}</div>
                    {{ if ne .CreatedAt .UpdatedAt }}
                        <div>
                            <p>
                                <i>Last edited on
                                    <time datetime="{{ iso8601Time .UpdatedAt }}"
                                          title="{{ timeAgo .UpdatedAt }}">{{ iso8601Time .UpdatedAt }}</time>
                                </i>
                            </p>
                        </div>
                    {{ end }}
                    {{ if .User.About }}
                        <div class="signature">
                            {{ sig .User.About }}
                        </div>
                    {{ end }}
                </td>
            </tr>
        {{ end }}
        </tbody>
    </table>
    {{ if .board.Forum.IsLocked }}
        <p>This forum is locked.</p>
    {{ end }}
    {{ if .board.IsLocked }}
        <p>This board is locked.</p>
    {{ end }}
    {{ if .topic.IsLocked }}
        <p>This topic is locked.</p>
    {{ end }}
    {{ if logged }}
        {{ if or (and (not .topic.IsLocked) (not .board.IsLocked) (not .board.Forum.IsLocked)) .logged.IsAdmin }}
            <section style="margin-top: 1em;">
                {{ if .errorMessage }}
                    <p class="errors">{{ .errorMessage }}</p>
                {{ end }}
                <form action="/posts/save" method="post">
                    {{ .csrfField }}
                    <input type="hidden" name="topicId" value="{{ .topic.Id }}">
                    <input type="hidden" name="boardId" value="{{ .board.Id }}">
                    <input type="hidden" name="subject" value="Re: {{ .topic.Post.Subject }}">
                    <div class="field">
                        <label for="content">Reply to this topic</label>
                        <textarea name="content" id="content" style="height: 150px;"></textarea>
                    </div>
                    <input type="submit" value="Reply">
                </form>
            </section>
        {{ end }}
    {{ end }}
{{ end }}
`,
}
